### ISSUE TITLE
大神，是不是有接口不能调用了

### ISSUE THREAD

**Issue by Tyran820** [callmefeifei/baby-names#2]
8月份试用的时候挺好用的，现在再用不好使了，输出完总数就不动了，也没有提示。现在人在医院，手机ssh云上的服务器执行的，不方便调试具体分析。

**Comment by callmefeifei** [comment]
> 8月份试用的时候挺好用的，现在再用不好使了，输出完总数就不动了，也没有提示。现在人在医院，手机ssh云上的服务器执行的，不方便调试具体分析。

我跑了下是可以的噢～

**Comment by Tyran820** [comment]
> > 8月份试用的时候挺好用的，现在再用不好使了，输出完总数就不动了，也没有提示。现在人在医院，手机ssh云上的服务器执行的，不方便调试具体分析。
> 
> 我跑了下是可以的噢～

多谢！我闲下来看了下代码，我的问题，程序在跑，半天没一个够分数的名字，所以没输出，就以为卡住了呢。我还是慢慢跑吧。
