### ISSUE TITLE
python2.7 安装 gevent失败

### ISSUE THREAD

**Issue by Colbert337** [callmefeifei/baby-names#8]
求大神帮忙看看，系统是ubuntu64

安装报错如下:
`ubuntu@VM-92-69-ubuntu:~/baby-names$ sudo pip install -i http://pypi.douban.com/simple/ --trusted-host=pypi.douban.com -r docs/requirements.txtThe directory '/home/ubuntu/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/ubuntu/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting pypinyin (from -r docs/requirements.txt (line 1))
  Downloading http://pypi.doubanio.com/packages/db/50/58b16cb56aeb003246d76ce3648f8e449605d7595e444a9b7c87bd543db8/pypinyin-0.40.0-py2.py3-none-any.whl (1.3MB)
    100% |████████████████████████████████| 1.3MB 68.4MB/s 
Collecting cjklib (from -r docs/requirements.txt (line 2))
  Downloading http://pypi.doubanio.com/packages/05/6c/884b3e557bbdbf3beff896fefab3e8201a5b2a1732650cedaddd20115192/cjklib-0.3.2.tar.gz (17.4MB)
    100% |████████████████████████████████| 17.4MB 74.5MB/s 
Requirement already satisfied (use --upgrade to upgrade): BeautifulSoup4 in /usr/lib/python2.7/dist-packages (from -r docs/requirements.txt (line 3))
Collecting gevent (from -r docs/requirements.txt (line 4))
  Downloading http://pypi.doubanio.com/packages/0b/50/1b1175ea3a269b5fa3f0f7fed11149888180695bef5fbf568adbb196efaf/gevent-21.1.2.tar.gz (5.9MB)
    100% |████████████████████████████████| 5.9MB 64.7MB/s 
Requirement already satisfied (use --upgrade to upgrade): enum34; python_version < "3.4" in /usr/lib/python2.7/dist-packages (from pypinyin->-r docs/requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): typing; python_version < "3.5" in /usr/local/lib/python2.7/dist-packages (from pypinyin->-r docs/requirements.txt (line 1))
Collecting SQLAlchemy<0.7,>=0.6 (from cjklib->-r docs/requirements.txt (line 2))
  Downloading http://pypi.doubanio.com/packages/47/6f/de7020735ac188b759b8ba27f21fb1dcd76a52b3e88a181bc4b72bccd753/SQLAlchemy-0.6.9.tar.gz (2.2MB)
    100% |████████████████████████████████| 2.2MB 70.2MB/s 
Collecting greenlet<2.0,>=0.4.17; platform_python_implementation == "CPython" (from gevent->-r docs/requirements.txt (line 4))
  Downloading http://pypi.doubanio.com/packages/82/c7/760c570c083d6451ab0e2d806d7db7d1d845969f6fa20fd91dda692ae145/greenlet-1.0.0-cp27-cp27mu-manylinux1_x86_64.whl (148kB)
    100% |████████████████████████████████| 153kB 6.3MB/s 
Collecting cffi>=1.12.2; platform_python_implementation == "CPython" and sys_platform == "win32" (from gevent->-r docs/requirements.txt (line 4))
  Downloading http://pypi.doubanio.com/packages/ab/a7/1df1dcd222c9a35d2d0c4c123bd55a533ed2d07b09909ad085829deea4d6/cffi-1.14.5-cp27-cp27mu-manylinux1_x86_64.whl (389kB)
    100% |████████████████████████████████| 399kB 29.6MB/s 
Collecting zope.event (from gevent->-r docs/requirements.txt (line 4))
  Downloading http://pypi.doubanio.com/packages/9e/85/b45408c64f3b888976f1d5b37eed8d746b8d5729a66a49ec846fda27d371/zope.event-4.5.0-py2.py3-none-any.whl
Collecting zope.interface (from gevent->-r docs/requirements.txt (line 4))
  Downloading http://pypi.doubanio.com/packages/64/73/8de66bdab6c4494232339eba8f8864521180c9a76c7c6059b4202adb1e03/zope.interface-5.2.0-cp27-cp27mu-manylinux1_x86_64.whl (232kB)
    100% |████████████████████████████████| 235kB 95.9MB/s 
Requirement already satisfied (use --upgrade to upgrade): setuptools in /usr/lib/python2.7/dist-packages (from gevent->-r docs/requirements.txt (line 4))
Collecting pycparser (from cffi>=1.12.2; platform_python_implementation == "CPython" and sys_platform == "win32"->gevent->-r docs/requirements.txt (line 4))
  Downloading http://pypi.doubanio.com/packages/ae/e7/d9c3a176ca4b02024debf82342dab36efadfc5776f9c8db077e8f6e71821/pycparser-2.20-py2.py3-none-any.whl (112kB)
    100% |████████████████████████████████| 112kB 83.3MB/s 
Installing collected packages: pypinyin, SQLAlchemy, cjklib, greenlet, pycparser, cffi, zope.event, zope.interface, gevent
Killed
`

**Comment by callmefeifei** [comment]
> 求大神帮忙看看，系统是ubuntu64
> 
> 安装报错如下:
> `ubuntu@VM-92-69-ubuntu:~/baby-names$ sudo pip install -i http://pypi.douban.com/simple/ --trusted-host=pypi.douban.com -r docs/requirements.txtThe directory '/home/ubuntu/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag. The directory '/home/ubuntu/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag. Collecting pypinyin (from -r docs/requirements.txt (line 1)) Downloading http://pypi.doubanio.com/packages/db/50/58b16cb56aeb003246d76ce3648f8e449605d7595e444a9b7c87bd543db8/pypinyin-0.40.0-py2.py3-none-any.whl (1.3MB) 100% |████████████████████████████████| 1.3MB 68.4MB/s Collecting cjklib (from -r docs/requirements.txt (line 2)) Downloading http://pypi.doubanio.com/packages/05/6c/884b3e557bbdbf3beff896fefab3e8201a5b2a1732650cedaddd20115192/cjklib-0.3.2.tar.gz (17.4MB) 100% |████████████████████████████████| 17.4MB 74.5MB/s Requirement already satisfied (use --upgrade to upgrade): BeautifulSoup4 in /usr/lib/python2.7/dist-packages (from -r docs/requirements.txt (line 3)) Collecting gevent (from -r docs/requirements.txt (line 4)) Downloading http://pypi.doubanio.com/packages/0b/50/1b1175ea3a269b5fa3f0f7fed11149888180695bef5fbf568adbb196efaf/gevent-21.1.2.tar.gz (5.9MB) 100% |████████████████████████████████| 5.9MB 64.7MB/s Requirement already satisfied (use --upgrade to upgrade): enum34; python_version < "3.4" in /usr/lib/python2.7/dist-packages (from pypinyin->-r docs/requirements.txt (line 1)) Requirement already satisfied (use --upgrade to upgrade): typing; python_version < "3.5" in /usr/local/lib/python2.7/dist-packages (from pypinyin->-r docs/requirements.txt (line 1)) Collecting SQLAlchemy<0.7,>=0.6 (from cjklib->-r docs/requirements.txt (line 2)) Downloading http://pypi.doubanio.com/packages/47/6f/de7020735ac188b759b8ba27f21fb1dcd76a52b3e88a181bc4b72bccd753/SQLAlchemy-0.6.9.tar.gz (2.2MB) 100% |████████████████████████████████| 2.2MB 70.2MB/s Collecting greenlet<2.0,>=0.4.17; platform_python_implementation == "CPython" (from gevent->-r docs/requirements.txt (line 4)) Downloading http://pypi.doubanio.com/packages/82/c7/760c570c083d6451ab0e2d806d7db7d1d845969f6fa20fd91dda692ae145/greenlet-1.0.0-cp27-cp27mu-manylinux1_x86_64.whl (148kB) 100% |████████████████████████████████| 153kB 6.3MB/s Collecting cffi>=1.12.2; platform_python_implementation == "CPython" and sys_platform == "win32" (from gevent->-r docs/requirements.txt (line 4)) Downloading http://pypi.doubanio.com/packages/ab/a7/1df1dcd222c9a35d2d0c4c123bd55a533ed2d07b09909ad085829deea4d6/cffi-1.14.5-cp27-cp27mu-manylinux1_x86_64.whl (389kB) 100% |████████████████████████████████| 399kB 29.6MB/s Collecting zope.event (from gevent->-r docs/requirements.txt (line 4)) Downloading http://pypi.doubanio.com/packages/9e/85/b45408c64f3b888976f1d5b37eed8d746b8d5729a66a49ec846fda27d371/zope.event-4.5.0-py2.py3-none-any.whl Collecting zope.interface (from gevent->-r docs/requirements.txt (line 4)) Downloading http://pypi.doubanio.com/packages/64/73/8de66bdab6c4494232339eba8f8864521180c9a76c7c6059b4202adb1e03/zope.interface-5.2.0-cp27-cp27mu-manylinux1_x86_64.whl (232kB) 100% |████████████████████████████████| 235kB 95.9MB/s Requirement already satisfied (use --upgrade to upgrade): setuptools in /usr/lib/python2.7/dist-packages (from gevent->-r docs/requirements.txt (line 4)) Collecting pycparser (from cffi>=1.12.2; platform_python_implementation == "CPython" and sys_platform == "win32"->gevent->-r docs/requirements.txt (line 4)) Downloading http://pypi.doubanio.com/packages/ae/e7/d9c3a176ca4b02024debf82342dab36efadfc5776f9c8db077e8f6e71821/pycparser-2.20-py2.py3-none-any.whl (112kB) 100% |████████████████████████████████| 112kB 83.3MB/s Installing collected packages: pypinyin, SQLAlchemy, cjklib, greenlet, pycparser, cffi, zope.event, zope.interface, gevent Killed `

单独pip install gevent试试

**Comment by Colbert337** [comment]
pip不支持python2.7了，郁闷

**Comment by Colbert337** [comment]
已经解决了，1）通过增加swap解决pip install时内存分配不足导致失败的问题 2）在python2.7版本下要按照小于21版本的pip
