### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by plybb** [callmefeifei/baby-names#9]
哥们，运行generate_names.py后，提示SyntaxError: Missing parentheses in call to 'print'. Did you mean print(1111,err)?
怎么处理？

**Comment by callmefeifei** [comment]
> 哥们，运行generate_names.py后，提示SyntaxError: Missing parentheses in call to 'print'. Did you mean print(1111,err)?
> 怎么处理？

需要用python2环境执行

**Comment by plybb** [comment]
> > 哥们，运行generate_names.py后，提示SyntaxError: Missing parentheses in call to 'print'. Did you mean print(1111,err)?
> > 怎么处理？
> 
> 需要用python2环境执行

多谢，我用的是python3.x, 那我用旧版再测试一下。
